### ISSUE TITLE
Limited dimensioning possibilities for revolved objects (cone, cylinder)

### ISSUE THREAD

**Issue by kwahoo2** [ianrrees/FreeCAD_tinkering#12]
In https://github.com/WandererFan/freecad-dev/wiki

> some edges are missing "reference" to OCC edge. --> can't select and can't calculate dimensions. 
> not all projection edges have an equivalent in Source. (ex for a Sphere, projection has a circular edge, but Source Sphere has no circular edge)

The problem seems to be bigger. Cones and cylinders have [only one selectable](http://en.zimagez.com/full/27b89824ac7d91d7817defaa1cf6b754cf6dde686c3cbc2ae45b60d5b71b53d909f1f530e4ec584a.php) edge (slant height/height), two vertices and top/bottom circular edges. This makes eg. dimensioning cone angle impossible. 

Workaround ideas:
- add some additional OCC edges, vertices eg. 4 slant height edges (0, 90, 180 and 270 deg) - may be tricky, and will be a waste of resources
- use 2D edges edges after projection, similar to Hamish's python Drawing Dimensioning workbench - only for projected edges, mess on code and in FCstd file
- other ideas?

**Comment by WandererFan** [comment]
The current approach only allows edges that exist in the Source object to be selected in the Drawing.  Should just prevent making a "True" dimension is the Edge doesn't exist in the Source.
