### ISSUE TITLE
Fix regression - moving front view with measurement highlighted

### ISSUE THREAD

**Issue by ianrrees** [ianrrees/FreeCAD_tinkering#6]
Caused by the front view not stealing focus from anything other than views, or perhaps that's not the right approach anyways.  -Ian-

**Comment by WandererFan** [comment]
For clarity: if a dimension on View001 is highlighted,  then Orthoview001(Front) is clicked to move, the dimension in View001 remains highlighted and and is moved in conjunction with Front.  Guess that SelectionChanged is not being triggered for the Dimension.

**Comment by ianrrees** [comment]
Yes, exactly.  I went ahead and fixed it - my earlier "solution" turns out to be much more complicated than necessary... Go figure.
